// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD32dlHD53IfOcUTsEYDYxWR4t7gSRr8FA',
    appId: '1:597534191579:web:b98ace77f6530afe0441fe',
    messagingSenderId: '597534191579',
    projectId: 'login-dart',
    authDomain: 'login-dart.firebaseapp.com',
    storageBucket: 'login-dart.appspot.com',
    measurementId: 'G-GYHMYH6VDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfhg-Ff2OOS3zphtWQphGLMUl8ftVh0mA',
    appId: '1:597534191579:android:ec275566b0ed4a230441fe',
    messagingSenderId: '597534191579',
    projectId: 'login-dart',
    storageBucket: 'login-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiOk7N3dG2jplFm_QGmDq3KLSU13aLWOI',
    appId: '1:597534191579:ios:21e42b9842d7c0090441fe',
    messagingSenderId: '597534191579',
    projectId: 'login-dart',
    storageBucket: 'login-dart.appspot.com',
    iosBundleId: 'com.example.loginDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiOk7N3dG2jplFm_QGmDq3KLSU13aLWOI',
    appId: '1:597534191579:ios:9b8abd81cb19b4340441fe',
    messagingSenderId: '597534191579',
    projectId: 'login-dart',
    storageBucket: 'login-dart.appspot.com',
    iosBundleId: 'com.example.loginDart.RunnerTests',
  );
}
